export const content = {
  title: "Home // घर",
  description: {
    eng: 
    `"Please come here, Rinku. Go wash your hands. Let’s eat Imrati and Dhokla. They gave plenty of chilies with it. Keep that (phone) aside, why do you keep taking pictures? Who takes interest the personal pictures? Take this. Eat it. Let that be.” My mother asks me to share the sweets on her plate as she disregards my preoccupation with taking random pictures of our familial experiences in the house. \n\nPhotographing my parents has been a private experience for me. It has helped me feel my vision consciously. That experience has allowed a serendipitous exchange between the act of taking their photographs and the act of reflecting on my vision. The photographs had helped me bridge the way my parents behave around me and the way I see them. Initially, I started taking their pictures with an intention to record my mother’s recovery from schizophrenia and my father’s recovery from long term depression. Although, the act of photographing them has mostly been helping me to visually articulate and re-establish the emotional intimacy in my relationship with them. \n\nMy parents don’t share similar relationship with photography. Beyond looking at it as a risky and avoidable career choice of their only offspring, they don’t share anything personal with documentary photography. They routinely express their anxiety about my career choice, which in turn also induces my personal anxiety about economic sustainability. As an eldest son of a landless dalit in Vidarbha, my father secured upper mobility as graduated lower middle class government employee in Marathwada. He is also now a father to son with an elite higher education and yet without any conventional and active earning sources. My mother, who was asked to leave college to get married to my father, has closely seen educated men of her generation sit jobless as they failed to find employment in time. The inability to be always mindful of anxieties and to express verbally and communicate the feelings has always had a crippling effect on our familial environment. \n\nAs we are healing through generational and familial traumas together, I personally find the intentional and specific act of making a family portrait very burdening. Given the intimacy I lately lacked in my relationship with my parents, I am often scared of ending up making an awkward image without any candidness in it. Yet more than the grand image of togetherness itself, I am more hopeful and curious about the inclusive act of looking at the family pictures together. The essence of family albums and healing potential in the physical images will help the communication and intimacy within my family. For me, the ultimate aim of the engagement with photography is to heal and beget self compassion. Taking my parents beyond the straightness and festivity in the making of conventional family portrait, I wish to share the wider possibilities with candidness, intimacy and normalcy in engaging with family albums.`,
    mar: 
    `"इकडे ये नं रिंकू. इकडे ये. हात धुवून ईमरती ढोकळा खाऊ. मिरचे तर बदबद दिले. राहू दे. काय फोटो घेतसं तं. घरचे कोणाला दाखवायचे? घे नं. खा नं. राहू दे ते.”  सोबत बसून फराळ खाणं सोडून मोबाइलमधे गुंतून आणि त्यातल्या त्यात उगीचं घरात फोटो काढत बसण्यात माझ्या आईला पटण्यासारखं काहीच नव्हतं. \n\nआईवडिलांचे फोटोज काढणे तशी माझ्यासाठी खूप व्यक्तीगत गोष्ट आहे. पण फोटो काढण्याच्या त्या निमित्ताने मला स्वतःची ‘नजर’ उमजायला लागली. स्वतःच्या मनाची झापडं आणि काढलेले फोटोज ह्यांची नकळतपणेच पडताळणी होऊ लागली. माझ्याभोवतीचे माझे आई-वडील आणि मला दिसणारे माझे आई-वडील ह्यांच्यातला दुवा म्हणून मला ते फोटोज कामी येऊ लागले. सुरुवातीला मला वाटलेलं कि आईची स्कीझोफ्रेनियातुन आणि पप्पांची दीर्घ नैराश्यातून होणारी सुधारणा मी 'डॉक्युमेन्ट’ करत आहे. खरं तर त्या फोटो काढण्यांतून मला आमचं डळमळलेलं नातं समजण्यासाठी-जुळवण्यासाठी भावनिक भाषा सापडत जात आहे. \n\nआईवडिलांचं तसं नाही आहे. एकुलत्या पोराचं सोंग आणि बिनकामाचं अवघड करियर ह्यांपलीकडे फोटोग्राफीला त्यांच्याशी जुळवून घ्यायला फारसं जमलेलं नाही. डॉक्युमेंटरी फोटोग्राफर म्हणून माझ्या करियरबद्दल त्यांची काळजी ते नेहमी बोलून दाखवतात. स्वतःच्या आर्थिक भवितव्याबद्दल चिंता करण्यापासून थोडी पळवाट काढण्याची मग मलाही उसंत मिळत नाही. तसं तर पप्पांनी स्वतः खूप प्रगती केली आहे. विदर्भातल्या खेड्यातल्या एका भूमिहीन दलिताचा सर्वात थोरला मुलगा ते मराठवड्यात पदवीधर-सरकारी नोकर-मध्यमवर्गीय असा त्यांचा प्रवास. अभिजनांचे अतिउच्चशिक्षण घेऊनहि कुठल्याही पारंपरिक आणि चालू आर्थिक स्त्रोत्यांशिवाय असलेल्या मुलाचे ते त्याचबरोबर वडीलदेखील आहेत. आईचं कॉलेज तसही लग्नामुळेच अर्धवट सुटलेलं होत, पण तिनेही तिच्या पिढीतले उच्चशिक्षित पुरुष वेळेत नोकरी न मिळाल्याने रिकामटेकडे बसलेले खूप जवळून पाहिले आहेत. जीवाला लागलेले घोर नेहमीच शब्दांत घालून ठेवता येतात किंवा भावनांना नेहमीच बडबडायला येतं असं नाही, पण तरीही नात्यांच्या पांगुळलेपणावर त्यामुळे व्हायचा तो परिणाम होतोच. \n\nपिढीजात आणि कौटुंबिक आघातांमधून भरून येताना मुद्दामहून काढायचे फॅमिली ग्रुप फोटो खूप तकलादू, दिखाऊ आणि थोडे कामचुकार वाटतात. किंवा ते मुद्दामहुन काढावे लागतात म्हणून फक्त खूप अवघड वाटत असावेत. नात्यांतून कोरडलेल्या जवळीकीला उसने घेऊन बसवून काढलेला फोटो त्यातल्या खऱ्या मोकळेपणा अभावी औपचारिकतेने आक्रसून गेलेला नसेल का? एकत्र कुटुंबाच्या फोटोपेक्षा मग एकत्रितपणे कुटुंबाचे फोटो बघणे जास्त आशादायक असेल का? नात्यांतली जवळीक भरून यायला आणि संवाद साध्य व्हायला अश्या फॅमिली अल्बमची मदत घेता येणे शक्य असते का? जखमा भरवून स्व-स्नेह रुजवणे हेच कलेशी असलेल्या नात्याचं माझ्यासाठी परमोच्च ध्येय. म्हणून एकत्र थेट आणि पारंपरिक फॅमिली पोर्ट्रेट घेण्याच्या सोहळ्यापलीकडे मोकळेपणा, जवळीक आणि सहजता असलेला साधाच फॅमिली अल्बम देता आला तर?`,
  },
}

export const videoSources = {
  background: "https://www.youtube.com/embed/llARFMPOTB0?start=1137&autoplay=1&mute=1&controls=0&loop=1&playlist=llARFMPOTB0&modestbranding=1&showinfo=0&rel=0",
  gallery: "https://www.youtube.com/embed/INBzyeMpWzo?autoplay=1&mute=1&controls=0&loop=1&playlist=INBzyeMpWzo&modestbranding=1&showinfo=0&version=3&playlist=INBzyeMpWzo&rel=0",
  galleryDuration: 118 // Duration in seconds (placeholder, should be actual video length)
}

export const timelineItems = [
  { timestamp: 0, label: 'Beginning' },
  { timestamp: 60, label: 'Memory' },
  { timestamp: 120, label: 'Reflection' },
  { timestamp: 180, label: 'Healing' },
  { timestamp: 240, label: 'Normalcy' },
  { timestamp: 300, label: 'End' }
]

export const acknowledgements = ["Alka", "Pallavi", "Printo Priting Services", "A Tailer from Murugeshpalya"]
